version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: customized_domain_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "localnode:192.168.1.132"